name: build

on:
  push:
    branches: ['trunk']
  pull_request:
    branches: ['trunk']
  workflow_dispatch:

jobs:
  build_multi_os:
    name: Build and test ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17 (Oracle)
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: oracle

    - name: Display Java version
      run: java -version

    - name: Display Javac version
      run: javac -version

    - name: Display Maven version
      run: mvn -version

    - name: Build
      run: mvn install -DskipTests=true -Dgpg.skip -B -V
    
    - name: Install Spice (https://install.spiceai.org) (Linux)
      if: matrix.os == 'ubuntu-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl https://install.spiceai.org | /bin/bash
        echo "$HOME/.spice/bin" >> $GITHUB_PATH
        $HOME/.spice/bin/spice install
    
    - name: Install Spice (https://install.spiceai.org) (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install spiceai/spiceai/spice
        brew install spiceai/spiceai/spiced

    - name: install Spice (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        curl -L "https://install.spiceai.org/Install.ps1" -o Install.ps1 && PowerShell -ExecutionPolicy Bypass -File ./Install.ps1

    - name: add Spice bin to PATH (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        Add-Content $env:GITHUB_PATH (Join-Path $HOME ".spice\bin")
      shell: pwsh

    - name: Init and start spice app (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        spice init spice_qs
        cd spice_qs
        spice add spiceai/quickstart
        spiced &> spice.log &
        # time to initialize added dataset
        sleep 10
    
    - name: Init and start spice app (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        spice init spice_qs
        cd spice_qs
        spice add spiceai/quickstart
        Start-Process -FilePath spice run
        # time to initialize added dataset
        Start-Sleep -Seconds 10
      shell: pwsh

    - name: Test
      run: mvn test -B
      env:
        API_KEY: ${{ secrets.SPICE_CLOUD_API_KEY }}

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - version: 11
            distribution: microsoft # OpenJDK build by Microsoft
          - version: 17
            distribution: microsoft # OpenJDK build by Microsoft
          - version: 21
            distribution: microsoft # OpenJDK build by Microsoft
          # setup-java supports Oracle JDS 17 and later
          # - version: 11
          #   distribution: oracle
          - version: 17
            distribution: oracle
          - version: 21
            distribution: oracle
          - version: 22
            distribution: oracle

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java.version }} (${{ matrix.java.distribution }})
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java.version }}
        distribution: ${{ matrix.java.distribution }}

    - name: Display Java version
      run: java -version

    - name: Display Javac version
      run: javac -version

    - name: Display Maven version
      run: mvn -version

    - name: Build
      run: mvn install -DskipTests=true -Dgpg.skip -B -V
    
    - name: Install Spice (https://install.spiceai.org)
      run: |
        curl https://install.spiceai.org | /bin/bash
        echo "$HOME/.spice/bin" >> $GITHUB_PATH

    - name: Init and start spice app
      run: |
        spice init spice_qs
        cd spice_qs
        spice add spiceai/quickstart
        spice run &> spice.log &
        # time to initialize added dataset
        sleep 10

    - name: Test
      run: mvn test -B
      env:
        API_KEY: ${{ secrets.SPICE_CLOUD_API_KEY }}
  